### ISSUE TITLE
Error when decompiling binary (2)

### ISSUE THREAD

**Issue by yangzao** [revng/revng-c#15] opened 2024-04-29 15:19 UTC
Files: 
[2.zip](https://github.com/revng/revng/files/15151291/2.zip)

Source code, compiled program, and full error messages are included.

**Description**:

When decompiling the program, rev.ng gives error:
``
Assertion failed at /builds/gitlab/revng/orchestra/orchestra/sources/revng-c/lib/DataLayoutAnalysis/Middleend/MergePointeesOfPointerUnion.cpp:45
isWellFormedPointer(Pointer)
``

Compiler used: MSVC with /Od
Version: 19.38.33134 for x64

**Comment by pfez** [comment] 2024-05-08 19:25
I cannot reproduce this on the current `develop` branch.

I ran:
```
revng artifact decompile-to-single-file orig.exe --analyze
```

Can you please try on the current `develop` branch of `revng` and `revng-c` and tell me if you can still reproduce?

Thanks!

**Comment by yangzao** [comment] 2024-05-12 21:16
Hi,

I tried this program with the current `develop` branch and it can be decompiled without errors.

But the program in another [issue](https://github.com/revng/revng/issues/383) still causes errors.

**Comment by pfez** [comment] 2024-05-13 07:16
Ok, thank you for the feedback.

I'm closing this issue because it seems to be fixed on the current `develop`, or at least it's not reproducible anymore.
We'll take care of the other issue you mentioned separately.

**Closed as not planned by pfez** 2024-05-13 07:16 UTC
